version: '3.8'

services:
  inception-vm:
    build: .
    container_name: inception-evaluation-vm
    privileged: true  # Required for Docker-in-Docker
    ports:
      - "443:443"     # HTTPS port for your inception project
      - "2222:22"     # SSH access if needed
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket
      - vm-data:/home/evaluator                    # Persistent home directory
    stdin_open: true   # Keep container interactive
    tty: true         # Allocate TTY
    restart: unless-stopped
    networks:
      - evaluation-net

volumes:
  vm-data:
    driver: local

networks:
  evaluation-net:
    driver: bridge
